services:
  postgres:
    image: postgres
    container_name: chezaida_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chezaida

  adminer:
    image: adminer
    container_name: chezaida_adminer
    restart: always
    ports:
      - 8080:8080

